options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: build-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/frontend:$SHORT_SHA
      - -f
      - cloudbuild/Dockerfile
      - .

  - id: push-image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/frontend:$SHORT_SHA

  - id: deploy-cloud-run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - acme-webapp
      - --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/frontend:$SHORT_SHA
      - --region=${_REGION}
      - --project=${_PROJECT_ID}
      - --platform=managed
      - --set-env-vars=DEPLOYED_BY=cloud-build
      - --service-account=${_RUNTIME_SA}

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/frontend:$SHORT_SHA
